-- 코드를 입력하세요
SELECT a.PRODUCT_ID, b.PRODUCT_NAME, SUM(b.PRICE * a.AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER AS a
JOIN FOOD_PRODUCT AS b
ON a.PRODUCT_ID = b.PRODUCT_ID
WHERE YEAR(a.PRODUCE_DATE) = 2022 AND MONTH(a.PRODUCE_DATE) = 5
GROUP BY a.PRODUCT_ID, b.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, a.PRODUCT_ID ASC