-- 코드를 입력하세요
# 7월꺼를 FLAVOR기준으로 합산 -> FIRST_HALF와 조인하기
SELECT a.FLAVOR
FROM FIRST_HALF AS a
JOIN (
SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR
    ) AS b
ON a.FLAVOR = b.FLAVOR
ORDER BY a.TOTAL_ORDER+b.TOTAL_ORDER DESC
LIMIT 3