-- 코드를 작성해주세요
# 프론트 스킬을 가진 스킬 필터링
SELECT DISTINCT a.ID, a.EMAIL, a.FIRST_NAME, a.LAST_NAME
FROM DEVELOPERS AS a
JOIN (
SELECT CODE
FROM SKILLCODES
WHERE CATEGORY = 'Front End'
) AS b
WHERE a.SKILL_CODE & b.CODE > 0
ORDER BY a.ID ASC