-- 코드를 입력하세요
SELECT a.DR_NAME, a.DR_ID, a.MCDP_CD, 
    DATE_FORMAT(a.HIRE_YMD, '%Y-%m-%d') AS HIRE_YMD
FROM DOCTOR AS a
WHERE a.MCDP_CD = 'CS'
OR a.MCDP_CD = 'GS'
ORDER BY a.HIRE_YMD DESC, a.DR_NAME ASC