-- 코드를 입력하세요
# 리뷰를 가장 많이 남긴사람
SELECT b.MEMBER_NAME, a.REVIEW_TEXT, DATE_FORMAT(a.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS a
JOIN MEMBER_PROFILE AS b
ON a.MEMBER_ID = b.MEMBER_ID
WHERE b.MEMBER_ID = (
SELECT MEMBER_ID
FROM REST_REVIEW
GROUP BY MEMBER_ID
ORDER BY COUNT(*) DESC
LIMIT 1
    )
ORDER BY REVIEW_DATE ASC, a.REVIEW_TEXT ASC