-- 코드를 작성해주세요
SELECT DISTINCT a.ID, a.EMAIL, a.FIRST_NAME, a.LAST_NAME
FROM DEVELOPERS AS a
JOIN SKILLCODES AS b
ON a.SKILL_CODE & b.CODE > 0
WHERE b.NAME = 'C#' OR b.NAME = 'Python'
ORDER BY a.ID ASC
