-- 코드를 작성해주세요
SELECT c.ID, d.FISH_NAME, c.LENGTH
FROM FISH_INFO AS c
JOIN (
    SELECT b.FISH_TYPE, b.FISH_NAME, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO AS a
    JOIN FISH_NAME_INFO AS b
    ON a.FISH_TYPE = b.FISH_TYPE
    GROUP BY b.FISH_TYPE, b.FISH_NAME
) AS d
ON c.FISH_TYPE = d.FISH_TYPE
WHERE c.LENGTH = d.MAX_LENGTH
ORDER BY c.ID ASC