-- 코드를 작성해주세요
SELECT SUM(c.SCORE) AS SCORE, b.EMP_NO, b.EMP_NAME, b.POSITION, b.EMAIL
FROM HR_DEPARTMENT as a
    JOIN HR_EMPLOYEES as b
    ON a.DEPT_ID = b.DEPT_ID
    JOIN HR_GRADE AS c
    ON b.EMP_NO = c.EMP_NO
GROUP BY b.EMP_NO, b.EMP_NAME, b.POSITION, b.EMAIL
ORDER BY SCORE DESC
LIMIT 1